### ISSUE TITLE
missing vector tutorials on macOS M1?

### ISSUE THREAD

**Issue by mich-elle-luna** [RedisInsight/Tutorials#55]
Hi, I installed on my macOS M1, but the vector tutorials are not included for some reason. 
![image](https://github.com/RedisInsight/Tutorials/assets/153109578/c8fbd7b6-3711-4ddb-8144-260bffc4cf7e)

**Comment by ViktarStarastsenka** [comment]
@mich-elle-luna , please restart Redis Insight and check them one more time.

**Comment by ViktarStarastsenka** [comment]
re-open the ticket if the issue still persists.
